### ISSUE TITLE
multilang feeds

### ISSUE THREAD

**Issue by bnomei** [bnomei/kirby3-feed#15]
**needs language here**
https://github.com/bnomei/kirby3-feed/blob/master/classes/Feed.php#L57

**Comment by kinkwilde** [comment]
Can you explain how I might go about doing this? I am using the virtual page method.

**Comment by bnomei** [comment]
this issue was a reminder for me to fix the cache not supporting multilang.
https://github.com/bnomei/kirby3-feed/blob/7bf0bdf54c83fdabab120f477f43d1662328737c/classes/Feed.php#L99

for multilang feed where each feed has a different language you might need to add the "page scope". like this `'language' => '*',` . but i have not tried this myself.
https://getkirby.com/docs/reference/system/options/routes
https://getkirby.com/docs/guide/routing#multi-language-setup
