### ISSUE TITLE
Should this not be RSS+XML for the correct header response?

### ISSUE THREAD

**Issue by kinkwilde** [bnomei/kirby3-feed#19]
https://github.com/bnomei/kirby3-feed/blob/7bf0bdf54c83fdabab120f477f43d1662328737c/classes/Feed.php#L167

**Comment by bnomei** [comment]
it should use the mime type detection.
https://github.com/getkirby/kirby/blob/master/src/Http/Response.php#L87
https://github.com/getkirby/kirby/blob/b8846772d3cc2fabe4e84c5b7f128dcd0b6e4202/src/Toolkit/Mime.php#L84

did you notice any issues? mime type not set to correctly?

**Comment by bnomei** [comment]
closing since no response for more than a month
