### ISSUE TITLE
Different settings for different data types?

### ISSUE THREAD

**Issue by dantz** [bnomei/kirby3-feed#28]
I'm pulling feed contents from two different pages containing two different types of content:

`$feed = page('videos','blog')`

Is there a way to make all video posts use `'textfield' => 'intro',` while the blog posts use `'textfield' => 'text',`?

**Comment by bnomei** [comment]
both no. but you could create a [pagemethod](https://getkirby.com/docs/reference/plugins/extensions/page-methods) `feedtext` and use that.

```php
Kirby::plugin('my/page-methods', [
    'pageMethods' => [
        'feedtext' => function () {
            return $this->template()->name() === 'video' ? $this->intro() : $this->text() ;
        }
    ]
]);


```
