### ISSUE TITLE
Pulling other fields, not just content_html

### ISSUE THREAD

**Issue by jonwgeorge** [bnomei/kirby3-feed#29]
Is there a way to pull other custom fields with this, not just content_html. Would like to use this as a basis for a calendar, but need to pull references to a start and end field as well.

**Comment by bnomei** [comment]
you can use a custom snippet and forward whatever data you need via the options

```php
$options = [
                    'title'       => 'Latest articles',
                    'description' => 'Read the latest news about our company',
                    'link'        => 'blog',
                    'mycustomvar' => page('other'),
                    'summaryField' => 'crazy', // use this field in you snippet <?= \Kirby\Toolkit\Xml::encode($item->{$summaryField}()) ?>
                    'snippet' => 'feedWithSummary', // site/snippets/feedWithSummary.php
                ];
                $feed = page('blog')->children()->listed()->flip()->limit(10)->feed($options);
                return $feed;
```
> At least thats how i think it should work. :sweat_smile:

**Comment by bnomei** [comment]
if you need real ICS files... this might be the better choice: https://github.com/bnomei/kirby3-ics

**Comment by dcschmid** [comment]
Is it possible to add an author or the article tags to the rss feed. I need it to send push notifications with articled.io.

**Comment by bnomei** [comment]
see #34 and #36. please use a custom snippet.
