### ISSUE TITLE
renders json output

### ISSUE THREAD

**Issue by demlak** [bnomei/kirby3-feed#34]
hey there.. i'm using this plugin with this theme: https://www.one.thezero.club/
as you can see here: https://www.ecovillage-hannover.de/test3/feed
the description is just the plan json field.. not thaaaaat good =)

also some code-snippets are also displayed, when using them inside journal entries

how to fix?

thx

**Comment by bnomei** [comment]
did you create a route to the virtual page to display the feed?
https://github.com/bnomei/kirby3-feed#usage

**Comment by demlak** [comment]
Hey.. 
thx for your answer..
this is the current output: https://www.ecovillage-hannover.de/feed

thats the route inside config:
```
    [
            'pattern' => 'feed',
            'method' => 'GET',
            'action'  => function () {
                $options = [
                    'title'       => 'rss Feed',
                    'description' => 'ecovillage hannover',
                    'link'        => 'journal'
                ];
                $feed = page('journal')->children()->listed()->flip()->limit(14)->feed($options);
                return $feed;
            }
        ]
```

**Comment by demlak** [comment]
using `toBlocks()` instead of `kirbytext()` in `kirby3-feed/snippets/feed/rss.php` fixes the issue..
any idea of doing this by not modifying the plugin, but inside config or so?

**Comment by bnomei** [comment]
please create a snippet and use `$item` to create the logic you need. you can make the plugin use your snippet via the $options.
