### ISSUE TITLE
Add more options to (json) feed

### ISSUE THREAD

**Issue by S1SYPHOS** [bnomei/kirby3-feed#36]
Like 'authors', 'icon', 'favicon' etc ..
See https://daringfireball.net/feeds/json as example

I guess a PR would be in order - let me know what you think!

**Comment by S1SYPHOS** [comment]
If it's alright with you, I'd like to add array / maybe blocks support to the default snippets, that something you'd be interested in?

**Comment by bnomei** [comment]
you can pass your own snippet name as an option and can do pretty much anything with the `$item` (aka the page) there. i want to keep the plugins default as simple as possible.

**Comment by S1SYPHOS** [comment]
I thought you might say that, thanks for your time and effort!
