### ISSUE TITLE
Add support for h-feed

### ISSUE THREAD

**Issue by MaluNoPeleke** [bnomei/kirby3-feed#40]
Can you add support for [h-feeds](http://microformats.org/wiki/h-feed)?

**Comment by bnomei** [comment]
i want to avoid adding more and more formats. unless they are globally more in use than rss and atom. 

see #34 and #36. please use a custom snippet to add h-feeds. feel free to open this issue again if you get stuck doing so. i will try to help yout with that then step by step.

**Comment by MaluNoPeleke** [comment]
I came up with this simple code in a hfeed.php at top-level but I am not sure if it is okay and valid as I cannot find a real h-feed validator except [for this one](https://monocle.p3k.io/preview):

```
<?php snippet('header') ?>

<main>
  <header>
    <h1><?= $page->title() ?></h1>
  </header>


  <div class="h-feed">
    <h1 class="p-name"><a href="<?= $page->url() ?>" class="u-url">Pelekes Blog</a></h1>
    <?php foreach (page('blog')->children()->listed()->flip() as $item): ?>
    <article>
      <header class="article-header h-entry">
      <time><?= $item->date()->toDate('%d.%m.%Y') ?></time>
        <a href="<?= $item->url() ?>" class="u-url">
          <h2 class="p-name"><?= $item->title() ?></h2>
        </a>
      </header>
      <p><?= $item->description() ?></p>
    </article>
    </br>
    <?php endforeach ?>
    <a class="h-card u-url u-uid p-name">Frederik Niedernolte</a>
  </div>

</main>
<?php snippet('footer') ?>
```
