### ISSUE TITLE
Last Modified Date

### ISSUE THREAD

**Issue by clivewalker** [bnomei/kirby3-feed#42]
The Last Modified date in my sitemap.xml appears to be the same for all pages. The pages were created on different dates/times. Do I need to do something else here to output the accurate Last Modified dates for each page?

Thanks.

**Comment by texnixe** [comment]
Having the same issue. That is because the plugin used the date field or modified date of the first page in the list for all items.

**Comment by texnixe** [comment]
@clivewalker You can overwrite the snippet in  `/site/snippets/feed/sitemap.php` and replace

```
<lastmod><?= $modified ?></lastmod>

with
```
<lastmod><?= date('c', $item->modified()) ?></lastmod>
```

**Comment by clivewalker** [comment]
OK, that's fixed it. Thank you.
