### ISSUE TITLE
Is there a Comma missing?

### ISSUE THREAD

**Issue by engineerTrooper** [bnomei/kirby3-feed#44]
Hi,

is there a comma at the readme.md file missing? [https://github.com/bnomei/kirby3-feed#usage-sitemap](https://github.com/bnomei/kirby3-feed#usage-sitemap)
After I added the comma, my PHP file didn't crash anymore.

Code with correction:
`
...
    'modified' => time(),
    'snippet' => 'feed/sitemap',
    'mime' => null,
...
`

Best Regards
ET

**Comment by iskrisis** [comment]
@engineerTrooper yes there is a comma missing
