### ISSUE TITLE
Class 'Bnomei\Feed' not found

### ISSUE THREAD

**Issue by mauphie** [bnomei/kirby3-feed#50]
Just installed it works fine on my localhost. But when I put it on production, it returns the error on index.php: _Class 'Bnomei\Feed' not found_.

I have not touched any of the files in the plugin folder, just got it from Composer. and i just used the recommended code for my config files.

**Comment by bnomei** [comment]
if you install it with composer you will also have to publish the full vendor folder (not just upload the plugins folder). composer creates a lookup table and maybe if thats missing or out of date the class will not be found on your remote server.
