### ISSUE TITLE
[Feature Request] Add Snippet for Feed <link> Elements

### ISSUE THREAD

**Issue by luxlogica** [bnomei/kirby3-feed#6]
It would be super handy if the plugin also included a snippet that we could include in the `<head>` of the page that automatically adds the needed `<link>` elements for the feeds. Every time I do a blog I have to go back and search for the syntax, so something like `snippet('feed')` would be really helpful!

**Comment by bnomei** [comment]
i would like to keep it super basic. since setting up the route is not handled by the plugin nor will it provide help creating the link to it. the snippet would need params for title, link and mime which is pretty much same length as the required html. i updated the readme instead.
