### ISSUE TITLE
pubDate is invalid when date handler is set to strftime

### ISSUE THREAD

**Issue by LeBenLeBen** [bnomei/kirby3-feed#9]
In Kirby's config, you can change the date Handler to be `strftime` with `c::set('date.handler', 'strftime');`. In the context of a multi-lingual site, I need this to have translated dates.

This seems to break the "pubDate" value of the RSS feed as the date format used doesn't correspond to anything strftime knows. The output is simply raw:

```
<pubDate>r</pubDate>
```

**Comment by bnomei** [comment]
there is no `c::set` in k2, right? but https://getkirby.com/docs/reference/system/options/date
i am still investigating this.

**Comment by LeBenLeBen** [comment]
`c::set` still works in Kirby 3 even if it's not the recommended way anymore.

**Comment by bnomei** [comment]
same as #7. i think it is related to this:
https://github.com/getkirby/kirby/issues/1446

**Comment by bnomei** [comment]
will be fixed in kirby 3.0.2

**Comment by LeBenLeBen** [comment]
@bnomei I just installed 3.0.2 and the problem is still there. Shouldn't the "r" in `date('r', …)` be adapted in case of using strftime? It should be something like `%a, %d %b %Y %H:%M:%S %z` (I didn't found any shorthand), no?.

**Comment by bnomei** [comment]
so will i. in the meantime make sure to set global debug setting to true to deactivate the plugins cache.

**Comment by LeBenLeBen** [comment]
It seems to work when setting `'datefield'   => 'modified'` but not by default. I think it is caused by:

```
$item->{$datefield}()->toDate('r')
```

Which should not be `'r'` when using strftime. I have an idea on how to solve it and will submit a PR.

**Comment by bnomei** [comment]
https://github.com/bnomei/kirby3-feed/releases/tag/v1.1.1

**Comment by LeBenLeBen** [comment]
Thanks a lot!
